### ISSUE TITLE
Limit the ability to start new conversations

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/com.woltlab.wcf.conversation#112]
* [ ] Add a new permission that controls if users can start new conversations.
* [ ] This permission should not prevent the user from participating in existing conversations.

**Comment by jens1o** [comment]
Maybe set a limitation for a specific timeframe?

**Comment by dtdesign** [comment]
@jens1o This is already supported through the automatic user group assignments using the condition "registered for X days".

**Comment by jens1o** [comment]
I think you didn't got my point.

For example, users who bought my well-overpriced premium group should be able to start 6 conversations per day/week/month whereras my members who don't bought it only can start 1 conversation per month...

**Comment by dtdesign** [comment]
These kind of features do not fit into the very core of our products. You can however enforce this behavior using a plugin that dynamically adds them to a specific user group once they've exceeded their limit.
