### ISSUE TITLE
Add flood control for conversations

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/com.woltlab.wcf.conversation#135]
see WoltLab/WCF#3033
see https://community.woltlab.com/thread/274630-flood-control-f%C3%BCr-konversationen/

**Comment by dtdesign** [comment]
Depends on WoltLab/WCF#3033

**Comment by TimWolla** [comment]
Somewhat relevant: https://community.woltlab.com/thread/280505-use-consistent-wording-for-the-flood-control-options/ / WoltLab/WCF#3801
