### ISSUE TITLE
Non-activated users should not be able to use conversations by default

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/com.woltlab.wcf.conversation#197]
Conversations are potentially used for spam. Especially in communities where the admin manually activates users, non-activated users should not be allowed to create conversations.

The permissions should be set to "No" for the "Everyone" user group in the standard installation.

**Comment by aethior** [comment]
Hi @BurntimeX,

Currently non activated users also can:
- [ ] Write comments on user walls.
- [ ] Upload files to filebase.
- [ ] Create reviews on filebase.
- [ ] Create blog.
- [ ] Create articles in the blog.
- [ ] Create events in the calendar.
- [ ] Create albums in the gallery.
- [ ] Upload files to the gallery.

Have all these permissions also been checked?

Regards.
